### PR TITLE
reorder and edit Module Parameter section

### PR DESCRIPTION
**Pull request by cwhanse**

### CODE REVIEW

**Comment by toddkarin** [comment]
@cwhanse did you just reorder or did you also change descriptions?

**Comment by cwhanse** [comment]
> @cwhanse did you just reorder or did you also change descriptions?

Also revised some descriptions

**Comment by cwhanse** [comment]
Idk why, but the merge process struggles with text files. We occasionally see merge conflicts in .rst files in pvlib-python, when a line gets moved.

**Comment by cwhanse** [comment]
@toddkarin did the changes to variable names and definitions get dropped?

**Pull request merged**
