### PR TITLE
Issue 20 temperature units

### PR DESCRIPTION
**Pull request by mdeceglie**
See #20

### CODE REVIEW

**Comment by mdeceglie** [comment]
Thanks for resolving the conflicts. When I build the docs the degree symbol doesn't render correctly. I will push an update.

This is what I see:
Screen Shot 2020-07-13 at 12 26 47 PM

**Comment by mdeceglie** [comment]
Thanks for merging in `master`. It looks like this uses Â°C rather than °C. I will push an update.

**Comment by toddkarin** [comment]
I was playing with this. I found that this change makes it not possible to use excel to edit definitions.csv anymore. When excel saves the file, it adds extra characters and changes the encoding.

**Comment by mdeceglie** [comment]
Yes, excel corrupts data in all sorts of files and should not be used for things like this

**Comment by silverman** [comment]
Excel often saves csv files with an encoding that depends on the user's locale and operating system. This silently scrambles non-ASCII characters. Modern programs are expecting (assuming) the file to have been encoded with UTF-8. My opinion: whoever opens the file in Excel should just choose 'CSV UTF-8 (Comma delimited) (.csv)' as the file format in Excel's Save As dialog, instead of 'Comma Separated Values (.csv)'. This should avoid the scrambling of non-ASCII characters.

**Pull request merged**
